//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelFair {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelFair.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        internal static string AdultsText {
            get {
                return ResourceManager.GetString("AdultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string AllTitle {
            get {
                return ResourceManager.GetString("AllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        internal static string BookingTitle {
            get {
                return ResourceManager.GetString("BookingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string CancelledTitle {
            get {
                return ResourceManager.GetString("CancelledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age of child.
        /// </summary>
        internal static string ChildAge {
            get {
                return ResourceManager.GetString("ChildAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        internal static string ChildrenText {
            get {
                return ResourceManager.GetString("ChildrenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string DialogOk {
            get {
                return ResourceManager.GetString("DialogOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        internal static string DoneText {
            get {
                return ResourceManager.GetString("DoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred, try again.
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ExceptionTitle {
            get {
                return ResourceManager.GetString("ExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string FilterText {
            get {
                return ResourceManager.GetString("FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication error: {0}.
        /// </summary>
        internal static string HttpRequestExceptionMessage {
            get {
                return ResourceManager.GetString("HttpRequestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string HttpRequestExceptionTitle {
            get {
                return ResourceManager.GetString("HttpRequestExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past.
        /// </summary>
        internal static string PastTitle {
            get {
                return ResourceManager.GetString("PastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room 1.
        /// </summary>
        internal static string Room1Tetxt {
            get {
                return ResourceManager.GetString("Room1Tetxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room 2.
        /// </summary>
        internal static string Room2Text {
            get {
                return ResourceManager.GetString("Room2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room 3.
        /// </summary>
        internal static string Room3Text {
            get {
                return ResourceManager.GetString("Room3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room 4.
        /// </summary>
        internal static string Room4Text {
            get {
                return ResourceManager.GetString("Room4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH DEALS.
        /// </summary>
        internal static string SearchDealsText {
            get {
                return ResourceManager.GetString("SearchDealsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Here.
        /// </summary>
        internal static string SearchHereText {
            get {
                return ResourceManager.GetString("SearchHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        internal static string Sorttext {
            get {
                return ResourceManager.GetString("Sorttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        internal static string UpcomingTitle {
            get {
                return ResourceManager.GetString("UpcomingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where....
        /// </summary>
        internal static string WhereText {
            get {
                return ResourceManager.GetString("WhereText", resourceCulture);
            }
        }
    }
}
